/*
 * Binary array for the Web UI.
 * gzip is used for smaller size and improved speeds.
 * 
 * Please see https://github.com/Aircoookie/WLED/wiki/Add-own-functionality#web-ui
 * to find out how to easily modify the web UI source!
 */
 
// Autogenerated from wled00/data/index.htm, do not edit!!
const uint16_t PAGE_index_L = 0;
const uint8_t PAGE_index[] PROGMEM = {
};
